### PR TITLE
NPE on null parameter (fixes #823)

### LINKED ISSUE #823: Parameter annotation throws NullPointerException if dataset = null
Hi,

I have a negative test that takes in dataset with different values. Eg: null, empty string, invalid strings, etc. If i user @Parameter annotation provided by allure, it throws Null pointer Exception 
Here's the snippet of my test case and dataset

```
@Test(groups = TestGroups.Group1, dataProvider = "getInvalidCredentials")
    public void testInvalidLogin(@Parameter("username") String username,
            @Parameter("password") String password) {
        //do something with username and password
        }
    }
@DataProvider(name = "getInvalidCredentials")
    private Object[][] getInvalidCredentials() {
        return new Object[][] {
                                {null, null},
                                {"username", null}
               };
    }
```

Below is the stacktrace:

```
java.lang.NullPointerException at ru.yandex.qatools.allure.testng.AllureTestListener.fireAddParameterEvents(AllureTestListener.java:390)
    at ru.yandex.qatools.allure.testng.AllureTestListener.onTestStart(AllureTestListener.java:143)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1700)
    at org.testng.internal.Invoker.runTestListeners(Invoker.java:1675)
```

### PR DESCRIPTION
**Pull request by sseliverstov**

### CODE REVIEW

File: allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java [hunk 1]
```diff
@@ -457,7 +457,7 @@ private void fireAddParameterEvents(ITestResult iTestResult) {
             }
 
             String name = getNameForParameter(parameter.value(), methodParameterNames, i);
-            String value = parameters[i].toString();
+            String value = parameters[i] != null ? parameters[i].toString() : "null";
```
Comment (baev) [inline allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java]: you can use `Objects.toString(parameters[i])` instead

File: allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java [hunk 2]
```diff
@@ -28,12 +28,7 @@
 
 import java.lang.annotation.Annotation;
 import java.lang.reflect.Method;
-import java.util.ArrayList;
-import java.util.Collections;
-import java.util.HashSet;
-import java.util.List;
-import java.util.Set;
-import java.util.UUID;
+import java.util.*;
```
Comment (baev) [inline allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java]: remove this change
